services:
  backend:
    # Service name
    build: ./app
    container_name: beat-analyser-backend
    image: beat-analyser:latest
    # Map container port 80 to host port 80
    ports:
      - "80:80"
    # Mount host folders to container
    volumes:
      - ./uploads:/app/uploads
      - ./app/app.py:/app/app.py
      - ./app/templates:/app/templates
    # Restart policy - do not restart automatically
    restart: no
